spring.application.name=book-drop
server.port=8080

spring.datasource.url=jdbc:postgresql://db:5432/bookdrop
spring.datasource.username=postgres
spring.datasource.password=${DB_PASSWORD}
spring.datasource.driver-class-name=org.postgresql.Driver
